#!/bin/bash

cmd=$1
item=$2
todo=~/drive/todo.yaml

case $cmd in
	add) 
		lastNum=$(tail -1 $todo | gsed -r 's/(^[0-9]+)\. (.*)/\1/')
		if [ "$lastNum" != "" ] ; then
			echo "$(($lastNum + 1)). $item" >> $todo 
		fi
		;;
	rm) 
		name=$(cat $todo | fzf)
		if [ "$name" != "" ] ; then 
			echo "$name removed"
			gsed "/$name/d" -i $todo
		fi
		;;
	file)
		nvim $todo
		;;
	*) cat $todo ;;
esac
